### ISSUE TITLE
skeleton

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/ghminer#1]
let's create and release a skeleton to an `npm`, based on this: https://github.com/h1alexbel/samples-filter/issues/125

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#5](https://github.com/h1alexbel/ghminer/issues/5), [#6](https://github.com/h1alexbel/ghminer/issues/6), [#7](https://github.com/h1alexbel/ghminer/issues/7), [#8](https://github.com/h1alexbel/ghminer/issues/8), [#9](https://github.com/h1alexbel/ghminer/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#6](https://github.com/h1alexbel/ghminer/issues/6), [#7](https://github.com/h1alexbel/ghminer/issues/7), [#8](https://github.com/h1alexbel/ghminer/issues/8), [#9](https://github.com/h1alexbel/ghminer/issues/9) are still not solved; solved: [#5](https://github.com/h1alexbel/ghminer/issues/5).

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#6](https://github.com/h1alexbel/ghminer/issues/6), [#7](https://github.com/h1alexbel/ghminer/issues/7), [#8](https://github.com/h1alexbel/ghminer/issues/8) are still not solved; solved: [#5](https://github.com/h1alexbel/ghminer/issues/5), [#9](https://github.com/h1alexbel/ghminer/issues/9).
